<?php

// This file is generated by Composer
require_once '../vendor/autoload.php';

$client = new Github\Client();
$client->authenticate('stepanoff', 'ghjntrn123', 'http_password');

$commits = $client->api('repo')->commits()->all('mediasite', 'gpor', array('sha' => 'master'));
var_dump($commits);
//$repositories = $client->api('user')->repositories('ornicar');
?>